version: '3.9'
services:
  postgres:
    image: postgres:15
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
  graphql-yoga-server:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    working_dir: /usr/local/apps/recs
    command: bash -c "npx prisma migrate dev --name init && npm run dev"
    volumes:
      - ./src:/usr/local/apps/recs/src
      - ./prisma:/usr/local/apps/recs/prisma
    environment:
      - PORT=4000
      - NODE_ENV=development
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/recs?schema=recs&connect_timeout=3000
      - ETH_WSS_URI=wss://wss.hyperspace.node.glif.io/apigw/lotus/rpc/v0
      - ETH_HTTP_URI=https://api.hyperspace.node.glif.io/
      # It is recommended to deploy a new rec marketplace contract for your developer environment.
      # See https://github.com/polyphene/recs-contract
      - REC_MARKETPLACE_ADDRESS=0x6B8113878282838535988B1e9AE36F9AD3B2eB6d
      - DEPLOYMENT_BLOCK_HEIGHT=306310
      # Energy Web foundation related env
      - EWF_HTTP_URI=https://rpc.energyweb.org
      - REGISTRY_EXTENDED_ADDRESS=0x5651a7A38753A9692B7740CCeCA3824a4d33aEFb
      - BATCH_FACTORY_ADDRESS=0x2248a8e53c8cf533aeef2369fff9dc8c036c8900
    ports:
      # GraphQL GUI
      - "4000:4000"
    depends_on:
      postgres:
        condition: service_healthy
    links:
      - postgres
volumes:
  db_data: